XX
    XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX

    XXXXXXXX XXX XXX XXXXXX XXXXX

    XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XX XXX XXXXXX XXXXX XXX XXXXXXXX
    XXXXXXXXX XXXX XXX XXXXXXX XXX XXXXXXXX
XX
B BBBBBBB BBBBBBBBBBBBB
 _('Search') 
BBB BBBBBBBBBBBB B BBBBBBBBBBBB B BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XXX
  XXXXXXXXX
  XX XXXX XX XXXX XXXX XXXXXXX XXX XXXXXX XXXXX XXXXX XXXXXX XXXXXX
     XXXX XX XX XXXXXX XXX XXXXXXXXX XX XXXXXXXXX XX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  
BBBBBBBB
BBBBB BBBB
  XXXXXXXXXX
  XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
    XX XXXXXXXXXXXXX
      BBBBBXXXXXX XXXXXXXX XXXXXXXXXX XX XXXXXX XXX XXXXXX
      XXXXXXXXXXXXXXBBBBBBBB
    XXXX
  XXXXXX
  XXXXXXXXXXX

  BB BBBBBBBBBBBBBBBB
    XXXX _('Search Results') XXXXX
    BB BBB BBBBBBBBBBBBBB
      XXX _('Your search did not match any documents. Please make sure that all words are spelled correctly and that you\'ve selected enough categories.') XXXX
    BBBBB
  BBBBB
  XXXX XXXXXXXXXXXXXXXXXXXX
  BB BBBBBBBBBBBBBB
    XXXX
    BBB BBBBB BBBBBBBB BBBBBBB BB BBBBBBBBBBBBBB
      XXXX
        XX XXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXFXXXX
      XXXXX
    BBBBBB
    XXXXX
  BBBBB
  XXXXXX
BBBBBBBB
