language: python
sudo: false

matrix:
  include:
      env: DJANGO=4.2.*
    - python: 3.10
      env: DJANGO=5.2.*

    - python: 3.11
      env: DJANGO=4.2.*
    - python: 3.11
      env: DJANGO=5.2.*

    - python: 3.12
      env: DJANGO=4.2.*
    - python: 3.12
      env: DJANGO=5.2.*

    - python: 3.13
      env: DJANGO=5.2.*

install:
  - python dev.py -no-container
  - pip install -q Django==$DJANGO
  - python setup.py install

script: python runtests.py
