XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX

B BB BBBBBBBBBBB BBB BBBBBBBBBB BBB BBBBBBBBBB
  XXXX _('This Page') XXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXFX
           XXXXXXXXXXXXXXX _('Show Source') XXXXXXXXX
  B BB BBBBBBBBBBBBBBBBBB
    XXXXXX XXXXXXX
           XXXXXXXXXXXXXXX _('Show on GitHub') XXXXXXXXX
  B BBBBB
  B BB BBBBBBBBBBBBBBBBBB
    XXXXXX XXXXXXX
           XXXXXXXXXXXXXXX _('Edit on GitHub') XXXXXXXXX
  B BBBBB
  XXXXX
B BBBBB