name: Run tests

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          # Django 4.2 LTS
          - os: ubuntu-latest
            python-version: "3.10"
            django-version: "4.2"

          - os: ubuntu-latest
            python-version: "3.11"
            django-version: "4.2"

          - os: ubuntu-latest
            python-version: "3.12"
            django-version: "4.2"

          # Django 5.1
          - os: ubuntu-latest
            python-version: "3.10"
            django-version: "5.1"

          - os: ubuntu-latest
            python-version: "3.11"
            django-version: "5.1"

          - os: ubuntu-latest
            python-version: "3.12"
            django-version: "5.1"

          - os: ubuntu-latest
            python-version: "3.13"
            django-version: "5.1"

          # Django 5.2 LTS
          - os: ubuntu-latest
            python-version: "3.10"
            django-version: "5.2"

          - os: ubuntu-latest
            python-version: "3.11"
            django-version: "5.2"

          - os: ubuntu-latest
            python-version: "3.12"
            django-version: "5.2"

          - os: ubuntu-latest
            python-version: "3.13"
            django-version: "5.2"

          # Django 6.0
          - os: ubuntu-latest
            python-version: "3.12"
            django-version: "6.0"

          - os: ubuntu-latest
            python-version: "3.13"
            django-version: "6.0"

          - os: ubuntu-latest
            python-version: "3.14"
            django-version: "6.0"

        fail-fast: false

    steps:
      - name: Install system dependencies (windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: zlib

      - uses: actions/checkout@v6.0.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python dev.py -no-container
          pip install -q Django==${{ matrix.django-version }}
          python -m pip install --upgrade pip
          pip install -U setuptools
          pip install -r requirements.txt
          python setup.py install

      - name: Test with pytest
        run: |
          python runtests.py
